import { IStateDeleteMessage } from ".//iStateDeleteMessage";
import { IStateEditMessageCaption } from ".//iStateEditMessageCaption";
import { IStateEditMessageMedia } from ".//iStateEditMessageMedia";
import { IStateEditMessageReplyMarkup } from ".//iStateEditMessageReplyMarkup";
import { IStateEditMessageText } from ".//iStateEditMessageText";
import { IStateStopPoll } from ".//iStateStopPoll";
import { IStateAddStickerToSet } from "./iStateAddStickerToSet";
import { IStateAnswerCallbackQuery } from "./iStateAnswerCallbackQuery";
import { IStateAnswerInlineQuery } from "./iStateAnswerInlineQuery";
import { IStateAnswerPreCheckoutQuery } from "./iStateAnswerPreCheckoutQuery";
import { IStateAnswerShippingQuery } from "./iStateAnswerShippingQuery";
import { IStateChosenInlineResult } from "./iStateChosenInlineResult";
import { IStateCreateNewStickerSet } from "./iStateCreateNewStickerSet";
import { IStateDeleteStickerFromSet } from "./iStateDeleteStickerFromSet";
import { IStateDeleteWebhook } from "./iStateDeleteWebhook";
import { IStateGetChatMember } from "./iStateGetChatMember";
import { IStateGetGameHighScores } from "./iStateGetGameHighScores";
import { IStateGetStickerSet } from "./iStateGetStickerSet";
import { IStateGetUpdates } from "./iStateGetUpdates";
import { IStateGetWebhookInfo } from "./iStateGetWebhookInfo";
import { IStateInlineQuery } from "./iStateInlineQuery";
import { IStateMessage } from "./iStateMessage";
import { IStateSendAudio } from "./iStateSendAudio";
import { IStateSendGame } from "./iStateSendGame";
import { IStateSendInvoice } from "./iStateSendInvoice";
import { IStateSendMessage } from "./iStateSendMessage";
import { IStateSendSticker } from "./iStateSendSticker";
import { IStateSendVideo } from "./iStateSendVideo";
import { IStateSetGameScore } from "./iStateSetGameScore";
import { IStateSetPassportDataErrors } from "./iStateSetPassportDataErrors";
import { IStateSetStickerPositionInSet } from "./iStateSetStickerPositionInSet";
import { IStateSetWebhook } from "./iStateSetWebhook";
import { IStateUploadStickerFile } from "./iStateUploadStickerFile";
import { IStateYoutubeDownload } from "./iStateYoutubeDownload";
import { IStateYoutubeSearchList } from "./iStateYoutubeSearchList";
import { IStateYoutubeVideoList } from "./iStateYoutubeVideoList";

export interface IState {
  addStickerToSet: IStateAddStickerToSet;
  answerCallbackQuery: IStateAnswerCallbackQuery;
  answerInlineQuery: IStateAnswerInlineQuery;
  answerPreCheckoutQuery: IStateAnswerPreCheckoutQuery;
  answerShippingQuery: IStateAnswerShippingQuery;
  chosenInlineResult: IStateChosenInlineResult;
  createNewStickerSet: IStateCreateNewStickerSet;
  deleteMessage: IStateDeleteMessage;
  deleteStickerFromSet: IStateDeleteStickerFromSet;
  deleteWebhook: IStateDeleteWebhook;
  editMessageCaption: IStateEditMessageCaption;
  editMessageMedia: IStateEditMessageMedia;
  editMessageReplyMarkup: IStateEditMessageReplyMarkup;
  editMessageText: IStateEditMessageText;
  getChatMember: IStateGetChatMember;
  getGameHighScores: IStateGetGameHighScores;
  getStickerSet: IStateGetStickerSet;
  getUpdates: IStateGetUpdates;
  getWebhookInfo: IStateGetWebhookInfo;
  inlineQuery: IStateInlineQuery;
  message: IStateMessage;
  sendAudio: IStateSendAudio;
  sendGame: IStateSendGame;
  sendInvoice: IStateSendInvoice;
  sendMessage: IStateSendMessage;
  sendSticker: IStateSendSticker;
  sendVideo: IStateSendVideo;
  setGameScore: IStateSetGameScore;
  setPassportDataErrors: IStateSetPassportDataErrors;
  setStickerPositionInSet: IStateSetStickerPositionInSet;
  setWebhook: IStateSetWebhook;
  stopPoll: IStateStopPoll;
  uploadStickerFile: IStateUploadStickerFile;
  youtubeDownload: IStateYoutubeDownload;
  youtubeSearchList: IStateYoutubeSearchList;
  youtubeVideoList: IStateYoutubeVideoList;
}
