import { IStateAnswerCallbackQuery } from "./iStateAnswerCallbackQuery";
import { IStateAnswerInlineQuery } from "./iStateAnswerInlineQuery";
import { IStateAnswerPreCheckoutQuery } from "./iStateAnswerPreCheckoutQuery";
import { IStateAnswerShippingQuery } from "./iStateAnswerShippingQuery";
import { IStateChosenInlineResult } from "./iStateChosenInlineResult";
import { IStateDeleteWebhook } from "./iStateDeleteWebhook";
import { IStateGetChatMember } from "./iStateGetChatMember";
import { IStateGetGameHighScores } from "./iStateGetGameHighScores";
import { IStateGetUpdates } from "./iStateGetUpdates";
import { IStateGetWebhookInfo } from "./iStateGetWebhookInfo";
import { IStateInlineQuery } from "./iStateInlineQuery";
import { IStateMessage } from "./iStateMessage";
import { IStateSendAudio } from "./iStateSendAudio";
import { IStateSendGame } from "./iStateSendGame";
import { IStateSendInvoiceQuery } from "./iStateSendInvoiceQuery";
import { IStateSendMessage } from "./iStateSendMessage";
import { IStateSendVideo } from "./iStateSendVideo";
import { IStateSetGameScoreQuery } from "./iStateSetGameScoreQuery";
import { IStateSetPassportDataErrors } from "./iStateSetPassportDataErrors";
import { IStateSetWebhook } from "./iStateSetWebhook";
import { IStateYoutubeDownload } from "./iStateYoutubeDownload";
import { IStateYoutubeSearchList } from "./iStateYoutubeSearchList";
import { IStateYoutubeVideoList } from "./iStateYoutubeVideoList";

export interface IState {
  answerCallbackQuery: IStateAnswerCallbackQuery;
  answerInlineQuery: IStateAnswerInlineQuery;
  answerPreCheckoutQuery: IStateAnswerPreCheckoutQuery;
  answerShippingQuery: IStateAnswerShippingQuery;
  chosenInlineResult: IStateChosenInlineResult;
  deleteWebhook: IStateDeleteWebhook;
  getChatMember: IStateGetChatMember;
  getGameHighScores: IStateGetGameHighScores;
  getUpdates: IStateGetUpdates;
  getWebhookInfo: IStateGetWebhookInfo;
  inlineQuery: IStateInlineQuery;
  message: IStateMessage;
  sendAudio: IStateSendAudio;
  sendGame: IStateSendGame;
  sendInvoiceQuery: IStateSendInvoiceQuery;
  sendMessage: IStateSendMessage;
  sendVideo: IStateSendVideo;
  setGameScoreQuery: IStateSetGameScoreQuery;
  setPassportDataErrors: IStateSetPassportDataErrors;
  setWebhook: IStateSetWebhook;
  youtubeDownload: IStateYoutubeDownload;
  youtubeSearchList: IStateYoutubeSearchList;
  youtubeVideoList: IStateYoutubeVideoList;
}
