import { initialState } from "./store";

describe("store utils", (): void => {
  test("should handle initialState", (): void => {
    expect(initialState).toEqual({
      youtubeDownloadResultInsert: {},
      youtubeDownloadResultFind: {},
      addStickerToSet: {},
      answerCallbackQuery: {},
      answerInlineQuery: {},
      answerPreCheckoutQuery: {},
      answerShippingQuery: {},
      callbackQueryDataFind: {},
      callbackQueryDataInsert: {},
      chosenInlineResult: {},
      commandUI: {
        future: [],
        past: [],
        present: {}
      },
      createNewStickerSet: {},
      deleteChatPhoto: {},
      deleteChatStickerSet: {},
      deleteMessage: {},
      deleteStickerFromSet: {},
      deleteWebhook: {},
      editMessageCaption: {},
      editMessageLiveLocation: {},
      editMessageMedia: {},
      editMessageReplyMarkup: {},
      editMessageText: {},
      exportChatInviteLink: {},
      forwardMessage: {},
      getChat: {},
      getChatAdministrators: {},
      getChatMember: {},
      getChatMembersCount: {},
      getFile: {},
      getGameHighScores: {},
      getMe: {},
      getStickerSet: {},
      getUpdates: {},
      getUserProfilePhotos: {},
      getWebhookInfo: {},
      inlineQuery: {},
      kickChatMember: {},
      leaveChat: {},
      message: {},
      pinChatMessage: {},
      promoteChatMember: {},
      restrictChatMember: {},
      sendAnimation: {},
      sendAudio: {},
      sendChatAction: {},
      sendContact: {},
      sendDocument: {},
      sendGame: {},
      sendInvoice: {},
      sendLocation: {},
      sendMediaGroup: {},
      sendMessage: {},
      sendPhoto: {},
      sendPoll: {},
      sendSticker: {},
      sendVenue: {},
      sendVideo: {},
      sendVideoNote: {},
      sendVoice: {},
      setChatDescription: {},
      setChatPhoto: {},
      setChatStickerSet: {},
      setChatTitle: {},
      setGameScore: {},
      setPassportDataErrors: {},
      setStickerPositionInSet: {},
      setWebhook: {},
      shortenList: {},
      shortenReset: {},
      stopMessageLiveLocation: {},
      stopPoll: {},
      unbanChatMember: {},
      unpinChatMessage: {},
      uploadStickerFile: {},
      youtubeDownload: {},
      youtubeSearchList: {},
      youtubeVideoList: {}
    });
  });
});
